
permalink: /:year-:month-:day-:title/
markdown: kramdown
encoding: utf-8

# 作者信息
author: 
  name: Sinsy
  email: 1214440709@qq.com
  link: http://www.sinsy.top
  # weibo: http://weibo.com/liqing215
  github: http://github.com/sinsy
  github_name: sinsy
  # twitter: https://twitter.com/jekyllrb

#网站信息
title: sinsy的博客
description: > # this means to ignore newlines until "baseurl:"
  当一天猿媛，敲一天代码
baseurl: "" # the subpath of your site, e.g. /blog
articleurl: "#"
url: "http://www.sinsy.top" # the base hostname & protocol for your site
github_username:  sinsy
rss_url: /pages/feed.xml


# 中文本地化
locals:
  tags: 标签
  about: 关于
  archive: 归档
  ukulele: 小尤
  resume: 个人简历
  demo: DEMO
  book: 读书
# 主题设置，自动激活某个标签
active: 全部文章

# 代码高亮：google-code-prettify